//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGestionArticulo_Almacen.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionArticuloEntities : DbContext
    {
        public GestionArticuloEntities()
            : base("name=GestionArticuloEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TableArticulo> TableArticulo { get; set; }
        public virtual DbSet<TableDetalleEntradas> TableDetalleEntradas { get; set; }
        public virtual DbSet<TableDetalleSalidas> TableDetalleSalidas { get; set; }
        public virtual DbSet<TableSalidas> TableSalidas { get; set; }
        public virtual DbSet<TableUsuarios> TableUsuarios { get; set; }
        public virtual DbSet<TableAlmacenes> TableAlmacenes { get; set; }
        public virtual DbSet<TableEntradas> TableEntradas { get; set; }
    }
}
