//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGestionArticulo_Almacen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableUsuarios
    {
        public int idusuario { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
        public int idrol { get; set; }
        public Nullable<System.DateTime> fechacreacion { get; set; }
        public Nullable<System.DateTime> fechaSalida { get; set; }
        public Nullable<System.DateTime> fechanacimiento { get; set; }
        public Nullable<int> idcreador { get; set; }
        public Nullable<int> idusuariomodifico { get; set; }
        public byte[] foto { get; set; }
        public string Status { get; set; }
        public string maquinaName { get; set; }
        public string ipmaquina { get; set; }
    }
}
