//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGestionArticulo_Almacen.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TableEntradas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableEntradas()
        {
            this.TableDetalleEntradas = new HashSet<TableDetalleEntradas>();
        }
    
        public int identrada { get; set; }
        [Required]
        public Nullable<int> numeroDocumento { get; set; }
        [Required]
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> descuento { get; set; }

        [Required]
        public Nullable<decimal> total { get; set; }
        public string comentario { get; set; }
        public string entregadopor { get; set; }
        public string enviadoa { get; set; }
        public string status { get; set; }
        public Nullable<int> idusuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableDetalleEntradas> TableDetalleEntradas { get; set; }
    }
}
