//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGestionArticulo_Almacen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableDetalleEntradas
    {
        public int iddetalle { get; set; }
        public int identrada { get; set; }
        public Nullable<int> iditem { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<int> idalmacen { get; set; }
        public string status { get; set; }
        public Nullable<int> idusuario { get; set; }
    
        public virtual TableArticulo TableArticulo { get; set; }
        public virtual TableEntradas TableEntradas { get; set; }
    }
}
