//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGestionArticulo_Almacen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableArticulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableArticulo()
        {
            this.TableDetalleEntradas = new HashSet<TableDetalleEntradas>();
            this.TableDetalleSalidas = new HashSet<TableDetalleSalidas>();
        }
    
        public int iditem { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idalmacen { get; set; }
        public Nullable<decimal> maximo { get; set; }
        public Nullable<decimal> minimo { get; set; }
        public Nullable<decimal> existencia { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> preciominimo { get; set; }
        public Nullable<decimal> itemdescuento { get; set; }
        public Nullable<decimal> itbis { get; set; }
        public Nullable<System.DateTime> vencimiento { get; set; }
        public string comentario { get; set; }
        public Nullable<int> idusuario { get; set; }
        public Nullable<int> idusuariomodifico { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableDetalleEntradas> TableDetalleEntradas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableDetalleSalidas> TableDetalleSalidas { get; set; }
        public virtual TableAlmacenes TableAlmacenes { get; set; }
    }
}
