//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGestionArticulo_Almacen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableAlmacenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableAlmacenes()
        {
            this.TableArticulo = new HashSet<TableArticulo>();
        }
    
        public int idalmacen { get; set; }
        public string nombre { get; set; }
        public Nullable<int> capacidad { get; set; }
        public string comentario { get; set; }
        public string status { get; set; }
        public Nullable<int> idusuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableArticulo> TableArticulo { get; set; }
    }
}
